[2025-09-24T09:09:35.041+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_data_cleanse_and_calculate_all.cleanse_data_h4 scheduled__2025-09-24T08:00:00+00:00 [queued]>
[2025-09-24T09:09:35.052+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_data_cleanse_and_calculate_all.cleanse_data_h4 scheduled__2025-09-24T08:00:00+00:00 [queued]>
[2025-09-24T09:09:35.053+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-24T09:09:35.067+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): cleanse_data_h4> on 2025-09-24 08:00:00+00:00
[2025-09-24T09:09:35.077+0000] {standard_task_runner.py:60} INFO - Started process 1662 to run task
[2025-09-24T09:09:35.082+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_data_cleanse_and_calculate_all', 'cleanse_data_h4', 'scheduled__2025-09-24T08:00:00+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/cleansing_data_flow.py', '--cfg-path', '/tmp/tmpb0miqdmp']
[2025-09-24T09:09:35.088+0000] {standard_task_runner.py:88} INFO - Job 252: Subtask cleanse_data_h4
[2025-09-24T09:09:35.273+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_data_cleanse_and_calculate_all.cleanse_data_h4 scheduled__2025-09-24T08:00:00+00:00 [running]> on host feaba2204362
[2025-09-24T09:09:35.440+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_data_cleanse_and_calculate_all' AIRFLOW_CTX_TASK_ID='cleanse_data_h4' AIRFLOW_CTX_EXECUTION_DATE='2025-09-24T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-24T08:00:00+00:00'
[2025-09-24T09:09:35.528+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/cleansing_data_flow.py", line 1612, in cleanse_data
    cursor.execute(insert_query, (
psycopg2.errors.StringDataRightTruncation: value too long for type character(1)

[2025-09-24T09:09:35.553+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag_data_cleanse_and_calculate_all, task_id=cleanse_data_h4, execution_date=20250924T080000, start_date=20250924T090935, end_date=20250924T090935
[2025-09-24T09:09:35.617+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 252 for task cleanse_data_h4 (value too long for type character(1)
; 1662)
[2025-09-24T09:09:35.669+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-24T09:09:35.788+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-24T09:59:31.147+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_data_cleanse_and_calculate_all.cleanse_data_h4 scheduled__2025-09-24T08:00:00+00:00 [queued]>
[2025-09-24T09:59:31.166+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_data_cleanse_and_calculate_all.cleanse_data_h4 scheduled__2025-09-24T08:00:00+00:00 [queued]>
[2025-09-24T09:59:31.167+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-24T09:59:31.183+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): cleanse_data_h4> on 2025-09-24 08:00:00+00:00
[2025-09-24T09:59:31.193+0000] {standard_task_runner.py:60} INFO - Started process 970 to run task
[2025-09-24T09:59:31.197+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_data_cleanse_and_calculate_all', 'cleanse_data_h4', 'scheduled__2025-09-24T08:00:00+00:00', '--job-id', '291', '--raw', '--subdir', 'DAGS_FOLDER/cleansing_data_flow.py', '--cfg-path', '/tmp/tmpwbmck28o']
[2025-09-24T09:59:31.202+0000] {standard_task_runner.py:88} INFO - Job 291: Subtask cleanse_data_h4
[2025-09-24T09:59:31.291+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_data_cleanse_and_calculate_all.cleanse_data_h4 scheduled__2025-09-24T08:00:00+00:00 [running]> on host 5d539c157d54
[2025-09-24T09:59:31.389+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_data_cleanse_and_calculate_all' AIRFLOW_CTX_TASK_ID='cleanse_data_h4' AIRFLOW_CTX_EXECUTION_DATE='2025-09-24T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-24T08:00:00+00:00'
[2025-09-24T09:59:31.533+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-24T09:59:31.541+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_data_cleanse_and_calculate_all, task_id=cleanse_data_h4, execution_date=20250924T080000, start_date=20250924T095931, end_date=20250924T095931
[2025-09-24T09:59:31.577+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-24T09:59:31.609+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
