[2025-09-23T03:02:54.016+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_mockup_test_raw_data_a1.insert_mock_data scheduled__2025-09-23T02:00:00+00:00 [queued]>
[2025-09-23T03:02:54.022+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_mockup_test_raw_data_a1.insert_mock_data scheduled__2025-09-23T02:00:00+00:00 [queued]>
[2025-09-23T03:02:54.022+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-23T03:02:54.031+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): insert_mock_data> on 2025-09-23 02:00:00+00:00
[2025-09-23T03:02:54.036+0000] {standard_task_runner.py:60} INFO - Started process 75 to run task
[2025-09-23T03:02:54.039+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_mockup_test_raw_data_a1', 'insert_mock_data', 'scheduled__2025-09-23T02:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/moc_data_flow.py', '--cfg-path', '/tmp/tmpt2u3an7s']
[2025-09-23T03:02:54.042+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask insert_mock_data
[2025-09-23T03:02:54.088+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_mockup_test_raw_data_a1.insert_mock_data scheduled__2025-09-23T02:00:00+00:00 [running]> on host cfb0b5fa7d2f
[2025-09-23T03:02:54.151+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_mockup_test_raw_data_a1' AIRFLOW_CTX_TASK_ID='insert_mock_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-23T02:00:00+00:00'
[2025-09-23T03:02:54.197+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/moc_data_flow.py", line 137, in insert_mock_data
    cursor.execute(
psycopg2.errors.NotNullViolation: null value in column "quantity_ALL" of relation "test_raw_data_a1" violates not-null constraint
DETAIL:  Failing row contains (16, 3.62, 1.96, 99, null, 80, 80, RUN                 , 2025-09-23 03:02:54.189759).

[2025-09-23T03:02:54.206+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag_mockup_test_raw_data_a1, task_id=insert_mock_data, execution_date=20250923T020000, start_date=20250923T030254, end_date=20250923T030254
[2025-09-23T03:02:54.215+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 9 for task insert_mock_data (null value in column "quantity_ALL" of relation "test_raw_data_a1" violates not-null constraint
DETAIL:  Failing row contains (16, 3.62, 1.96, 99, null, 80, 80, RUN                 , 2025-09-23 03:02:54.189759).
; 75)
[2025-09-23T03:02:54.252+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-23T03:02:54.265+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-23T03:15:32.114+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_mockup_test_raw_data_a1.insert_mock_data scheduled__2025-09-23T02:00:00+00:00 [queued]>
[2025-09-23T03:15:32.119+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_mockup_test_raw_data_a1.insert_mock_data scheduled__2025-09-23T02:00:00+00:00 [queued]>
[2025-09-23T03:15:32.119+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-23T03:15:32.127+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): insert_mock_data> on 2025-09-23 02:00:00+00:00
[2025-09-23T03:15:32.131+0000] {standard_task_runner.py:60} INFO - Started process 107 to run task
[2025-09-23T03:15:32.133+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_mockup_test_raw_data_a1', 'insert_mock_data', 'scheduled__2025-09-23T02:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/moc_data_flow.py', '--cfg-path', '/tmp/tmpno8f6090']
[2025-09-23T03:15:32.135+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask insert_mock_data
[2025-09-23T03:15:32.172+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_mockup_test_raw_data_a1.insert_mock_data scheduled__2025-09-23T02:00:00+00:00 [running]> on host 7555bbf85195
[2025-09-23T03:15:32.217+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_mockup_test_raw_data_a1' AIRFLOW_CTX_TASK_ID='insert_mock_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-23T02:00:00+00:00'
[2025-09-23T03:15:32.470+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-23T03:15:32.479+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_mockup_test_raw_data_a1, task_id=insert_mock_data, execution_date=20250923T020000, start_date=20250923T031532, end_date=20250923T031532
[2025-09-23T03:15:32.507+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-23T03:15:32.522+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-23T03:35:41.611+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_mockup_test_raw_data_a1.insert_mock_data scheduled__2025-09-23T02:00:00+00:00 [queued]>
[2025-09-23T03:35:41.616+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_mockup_test_raw_data_a1.insert_mock_data scheduled__2025-09-23T02:00:00+00:00 [queued]>
[2025-09-23T03:35:41.617+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-23T03:35:41.625+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): insert_mock_data> on 2025-09-23 02:00:00+00:00
[2025-09-23T03:35:41.630+0000] {standard_task_runner.py:60} INFO - Started process 85 to run task
[2025-09-23T03:35:41.633+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_mockup_test_raw_data_a1', 'insert_mock_data', 'scheduled__2025-09-23T02:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/moc_data_flow.py', '--cfg-path', '/tmp/tmp9__b2i9k']
[2025-09-23T03:35:41.635+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask insert_mock_data
[2025-09-23T03:35:41.671+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_mockup_test_raw_data_a1.insert_mock_data scheduled__2025-09-23T02:00:00+00:00 [running]> on host a9f18d8ac0d6
[2025-09-23T03:35:41.721+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_mockup_test_raw_data_a1' AIRFLOW_CTX_TASK_ID='insert_mock_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-23T02:00:00+00:00'
[2025-09-23T03:35:41.983+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-23T03:35:41.989+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_mockup_test_raw_data_a1, task_id=insert_mock_data, execution_date=20250923T020000, start_date=20250923T033541, end_date=20250923T033541
[2025-09-23T03:35:42.006+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-23T03:35:42.017+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
